<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CineAI.Application\CineAI.Application.csproj" />
    <ProjectReference Include="..\CineAI.Domain\CineAI.Domain.csproj" />
    <ProjectReference Include="..\..\services\CineAI.AI\CineAI.AI.csproj" />
    <ProjectReference Include="..\..\services\CineAI.Video\CineAI.Video.csproj" />
    <ProjectReference Include="..\..\services\CineAI.Storage\CineAI.Storage.csproj" />
    <ProjectReference Include="..\..\services\CineAI.Media\CineAI.Media.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
